FROM jenkins/jenkins:latest-jdk11

USER jenkins

RUN jenkins-plugin-cli --plugins     blueocean:1.27.16     
RUN jenkins-plugin-cli --plugins     build-timestamp:1.0.3     
RUN jenkins-plugin-cli --plugins     timestamper:1.17     
RUN jenkins-plugin-cli --plugins     pollscm:1.3.1     
RUN jenkins-plugin-cli --plugins     eddsa-api:latest   
RUN jenkins-plugin-cli --plugins     credentials     


USER root


RUN apt-get update
RUN apt-get install -y python3-pip

RUN apt-get update && \
    apt-get install -y python3-venv && \
    python3 -m venv /opt/venv


ENV PATH="/opt/venv/bin:$PATH"


RUN pip install --upgrade pip
COPY ./requirements.txt requirements.txt
COPY ./jenkins/jenkins-admin-password.txt jenkins-admin-password.txt
RUN pip3 install -r requirements.txt 
  

ENV FLUENTD_HOST "fluentd"
ENV FLUENTD_PORT "24224"
ENV JAVA_OPTS -Djenkins.install.runSetupWizard=false
ENV JENKINS_URL "http://jenkins:10000"
ENV ACCESS_KEY ${ACCESS_KEY}
ENV SECRET_KEY ${SECRET_KEY}


COPY jenkins/1-configureJenkins.groovy /usr/share/jenkins/ref/init.groovy.d/1-configureJenkins.groovy
COPY jenkins/2-addAccessKeys.groovy /usr/share/jenkins/ref/init.groovy.d/2-addAccessKeys.groovy

ENV PATH="/opt/venv/bin:$PATH"