  title: "Projeto CD4ML"
  image: "images/rossmann.jpg"
  link: "https://github.com/f-mtz/cd4ml-hands-on"
  description: Modelo de previsão de vendas com MLFlow.
  show_in_main_port: true
  show_in_credit_port: false
  topics:
    - "Previsão de Regressão"
    - "Mineração de sentimentos"
  tools:
    - "Python 3.11 e Pyenv"
    - "Pandas e Numpy"
    - "Flask e Streamlit"